#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export VISUAL='code --wait'
export EDITOR='code --wait'
export NVM_DIR="$HOME/.nvm"


# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# source any local envvars
[ -f ~/.local-env.zsh ] && source ~/.local-env.zsh
