# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init --path)"

# Gem dev paths
export PATH="/Users/yianl/Code/gem/bin:/Users/yianl/Code/arcanist/bin:$PATH"
# dotnet
export DOTNET_ROOT="/opt/homebrew/opt/dotnet/libexec"

# NVM
[ -f "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh

# Google Cloud SDK.
if [ -f '/Users/yianl/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/yianl/google-cloud-sdk/path.zsh.inc'; fi

# shell command completion for gcloud.
if [ -f '/Users/yianl/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/yianl/google-cloud-sdk/completion.zsh.inc'; fi

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# -----------------------------
# aliases
# -----------------------------
alias venv="source env/bin/activate"
alias guc="git reset --soft HEAD~"
alias gco="git checkout"
alias gs="git status"
alias gaa="git add ."
alias gcm="git commit -m"

function tma() {
  tmux new-session -s "$1" -A
}

# -------------------- Gem make dev-env
. "$HOME/.cargo/env"
export PATH="$PATH:$HOME/.cargo/bin"

# --------------------
# custom key bindings
# --------------------
bindkey -r "^L"  # disable ^L

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/yianl/.cache/lm-studio/bin"

# --- fzf-tab ---
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
